/** Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms. **/

fun main() {
    val limit = 4000000L
    fibonacciEvenNumbersSum(limit)

}

fun fibonacciEvenNumbersSum(limit:Long){
    var a = 1L
    var b = 2L
    var c:Long
    var result = 0L
    while (a < limit && b < limit) {
        c = a + b

        if (c % 2L == 0L)
            result += c

        a = b.also { b = c }
    }
    println(result+2)
}